# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar_url: images/avatar.jpg
resume_name: "Niket Naidu"
resume_title: "Embedded Systems Developer"
resume_header_intro: "My aim is to work in an environment that challenges my abilities and enables me to innovate and improve existing technologies. I wish to adapt myself to the growing surge in electronics worldwide and compete with my innovations on a global level while also continuously learning in my field."

# Add your label, font from fontawesome and color of the icon
resume_icon_links:
  - label: "Linkedin"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/niket-naidu-30090a134/"
    color: 2867B2
  - label: "Github"
    icon: "fab fa-github"
    url: "https://www.github.com/coder137"
    color: 211F1F
  - label: "GitLab"
    icon: "fab fa-gitlab"
    url: "https://gitlab.com/coder137"
    color: E24329
  - label: "Email"
    icon: "far fa-envelope"
    url: "mailto:niketnaiduus@gmail.com"
    color: B23121
  - label: "Website Blog"
    icon: "fas fa-rss"
    url: "https://coder137.github.io/blog/"
    color: EE802F

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: ""
resume_contact_address: ""

# Decide which sections to use
resume_section_skills: true
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_interests: true
resume_section_recognition: false
resume_section_associations: false
resume_section_links: false

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
